version: '3'

services:

  spring-app:
    image: sicredi-votes-v1:1.0.0
    ports:
      - "8080:8080"
    environment:
      - "SICREDI_VOTES_APPLICATION_PORT=80"
    depends_on:
      - mongo-db
    networks:
      - backend

  mongo-db:
    image: mongodb/mongodb-community-server:6.0-ubi8
    ports:
      - "27017:27017"
    networks:
      - backend

networks:
  backend: