spring:
  data:
    mongodb:
      uri: ${SICREDI_VOTES_DATABASE_URL:mongodb://mongo-db:27017/sicred-votes}
      username:
      password:
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer

topic:
  settings:
    seconds-to-expire-default: ${SECONDS-TO-EXPIRE-DEFAULT:60}

springdoc.packages-to-scan: org.edu.sicredi.votes.controller.v1
springdoc.swagger-ui.tryItOutEnabled: true
springdoc.swagger-ui.operationsSorter: method
springdoc.swagger-ui.tagsSorter: alpha
springdoc.swagger-ui.filter: true
springdoc.enable-data-rest: false